### ISSUE TITLE
Implement Error Tracking and Logging

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#26]
### User Story

As a developer,
I want comprehensive error tracking and logging
so that I can quickly identify and resolve issues in production.

---
### In Scope

- Integrate error tracking tool (e.g., Sentry)
- Set up logging for server-side and client-side errors
- Implement error categorization and prioritization

---
> Example
```javascript
// Using Sentry in a React app
import * as Sentry from "@sentry/react";

Sentry.init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",
  integrations: [new Sentry.BrowserTracing()],
  tracesSampleRate: 1.0,
});
```
---
### Acceptance Criteria:

- [ ] Error tracking tool integrated for both server and client
- [ ] Errors properly categorized and prioritized
- [ ] Automated alerts set up for critical errors
- [ ] Developers can easily access and analyze error logs
