### ISSUE TITLE
Implement Tiered PWA Audits in CI Pipeline

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#35]
### User Story (part of #18)

As a developer,
I want a tiered implementation of PWA audits in our CI pipeline
so that we can gradually improve our PWA capabilities without immediately breaking the build.

---
### In Scope

- Integrate Lighthouse CI into the GitHub Actions workflow
- Configure a tiered approach for PWA audits
- Set up reporting mechanism for audit results
- Implement a gradual increase in audit strictness

---
### Example Configuration

```json
lighthouserc.json
{
  "ci": {
    "collect": {
      "staticDistDir": "./dist"
    },
    "assert": {
      "assertions": {
        "service-worker": "warning",
        "installable-manifest": "warning",
        "works-offline": "warning",
        "offline-start-url": "off",
        "splash-screen": "off",
        "themed-omnibox": "off",
        "maskable-icon": "off",
        "apple-touch-icon": "off",
        "categories:pwa": ["warning", {"minScore": 0.5}]
      }
    }
  }
}
```

---
### Implementation Plan

Tier 1 (Essential PWA Features):

Implement and audit: service-worker, installable-manifest, works-offline
Set these to "warning" in Lighthouse CI config

Tier 2 (Enhanced Experience):

Implement and audit: offline-start-url, splash-screen, themed-omnibox
Update Lighthouse CI config to include these as "warning"

Tier 3 (Polish):

Implement and audit: maskable-icon, apple-touch-icon
Update Lighthouse CI config to include these as "warning"

---
Final Stage:

Set all assertions to "error"
Increase overall PWA category score threshold to 0.9

---
Acceptance Criteria:
- [x] Lighthouse CI is integrated into the GitHub Actions workflow
- [x] Initial configuration focuses on Tier 1 features with warnings
- [x] Audit reports are generated and accessible for each PR
- [ ] Developers receive notifications for failed audits (even if they don't block merging)
